### PR TITLE
Add refund support

### PR DESCRIPTION
**Pull request by Jellyfrog**
**Untested** - Don't merge yet
As per discussion with @delatbabel, will try to test it tomorrow

### CODE REVIEW

**Comment by delatbabel** [comment]
I have contacted support at PaymentWall and asked if they can implement partial refunds in the API -- with an amount parameter. Otherwise this is not really a refund, it's actually a void.

**Comment by Jellyfrog** [comment]
Paymentwall customer support said:
> https://api.paymentwall.com/api/brick/charge/$id/refund - will refund the amount back to users.
https://api.paymentwall.com/api/brick/charge/$id/void - will only void the payment either it will be manually credited or not. (This is common for recurring subscriptions)

**Comment by Jellyfrog** [comment]
@delatbabel ping?

**Comment by delatbabel** [comment]
According to Ivan this isn't correct. I think that to get a void from PaymentWall you have to call refund() in the PaymentWall library as the current VoidMessage currently does. The call to void() removes the transaction from the database at their end but does not actually credit the customer -- that has to be done manually by PW support.

I think that the expectation of VoidMessage is that it will credit the customer, which it currently does. This change takes away that credit to the customer so I think that it has to call refund() not void().

I have pinged Ivan about partial refunds, there is no plan to support that at the moment.

**Pull request closed without merging**
